# Generated by Django 3.2.13 on 2022-10-12 21:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('louvor', '0010_musica_chords'),
        ('playlist', '0002_playlist_playlist_createddate_playlist_playlist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistMusicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateField(blank=True, default=datetime.datetime.now)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='louvor.musica')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.playlist')),
            ],
        ),
    ]
