# Generated by Django 3.2.13 on 2022-10-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_playlistmusicas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_musicas',
        ),
    ]
