# Generated by Django 3.2.13 on 2022-10-13 05:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('louvor', '0010_musica_chords'),
        ('playlist', '0004_remove_playlist_playlist_musicas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistmusicas',
            options={'ordering': ['timestamp', 'order']},
        ),
        migrations.RemoveField(
            model_name='playlistmusicas',
            name='data_add',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_musicas',
            field=models.ManyToManyField(blank=True, through='playlist.PlaylistMusicas', to='louvor.Musica'),
        ),
        migrations.AddField(
            model_name='playlistmusicas',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playlistmusicas',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlistmusicas',
            name='musica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='louvor.musica'),
        ),
    ]
